### PR TITLE
Remove css and add pixelArt style.

### PR DESCRIPTION
**Pull request by gammafp**
I have removed the CSS from the html because I think that with the Phaser configuration tool you can add the pixelperfect.

Before: 
[https://gyazo.com/18d8ca8e7cdd2cc254dc8a918dda24a1](https://gyazo.com/18d8ca8e7cdd2cc254dc8a918dda24a1)

After: 
[https://gyazo.com/ad2343abac7ee8f60b05fc8e27ca5b6d](https://gyazo.com/ad2343abac7ee8f60b05fc8e27ca5b6d)

The map is finished.
[https://gyazo.com/23004a05cba6e3a8f78be25d3dffb6dc](https://gyazo.com/23004a05cba6e3a8f78be25d3dffb6dc)

### CODE REVIEW

**Comment by nkholski** [comment]
Thanks! I had a problem that tiles wasn't rendered properly when setting pixelArt to true. Can you confirm that the issue is gone: https://github.com/photonstorm/phaser/issues/3229? If so I'll absolutely merge your PR. I'd merge a solution where the tile sheet is fixed to solve the issue too, that the border pixels of each tile are repeated in a frame. 
I'd like to keep the margins of the body to 0 for when we can scale the game all over the window with the scale manager.

**Comment by gammafp** [comment]
No, it is not gone. It is a problem with the rendering of WEBGL.
If you change CANVAS, the problema is fixed.

CANVAS:
[https://gyazo.com/ffe569496c466a573e4bfa1ae8256fa3](https://gyazo.com/ffe569496c466a573e4bfa1ae8256fa3)

WEBGL:
[https://gyazo.com/172eb9707e22faff1a723bd1d961d89c](https://gyazo.com/172eb9707e22faff1a723bd1d961d89c)

**Comment by nkholski** [comment]
Ok. I don't want to lock the game to canvas, especially when tint (star) is dependent on WebGL. The best solution for clean pixels is to adapt the tilesheet.

**Comment by gammafp** [comment]
Yes,  the best solution is to adapt the tilesheet. Thank you for your project.

**Pull request closed without merging**
